name: ClientDetector
version: 2.5.3
author: Sportkanone123
main: de.sportkanone123.clientdetector.spigot.ClientDetector
load: POSTWORLD
api-version: 1.13

softdepend: [PlaceholderAPI, ProtocolLib, ViaVersion]

commands:
  clientdetector:
    aliases: cd
  client:
  forge:
  mods: